import 'dotenv/config';import bcrypt from 'bcryptjs';import {connectDB} from '../config/db.js';import User from '../models/User.js';import Book from '../models/Book.js';import BookCopy from '../models/BookCopy.js';import Setting from '../models/Setting.js';
await connectDB();await Promise.all([User.deleteMany({}),Book.deleteMany({}),BookCopy.deleteMany({}),Setting.deleteMany({})]);
const pass=async p=>bcrypt.hash(p,10);await User.insertMany([
{name:'Head Librarian',email:'admin@bookbank.com',password:await pass('Admin@123'),role:'admin'},
{name:'Keeper of the Archives',email:'librarian@bookbank.com',password:await pass('Librarian@123'),role:'librarian'},
{name:'Rethika Student',email:'student1@college.edu',password:await pass('Student@123'),role:'student',studentId:'JCE001',department:'Computer Science',year:4,section:'A',phone:'9000000001'},
{name:'Arun Student',email:'student2@college.edu',password:await pass('Student@123'),role:'student',studentId:'JCE002',department:'Information Technology',year:3,section:'B',phone:'9000000002'}
]);
const titles=[['Clean Code','Robert C. Martin','Software Engineering'],['The Pragmatic Programmer','Andrew Hunt','Software Engineering'],['Database System Concepts','Silberschatz','Computer Science'],['Computer Networks','Andrew S. Tanenbaum','Computer Science'],['Operating System Concepts','Silberschatz','Computer Science'],['Artificial Intelligence','Stuart Russell','Computer Science'],['Java: The Complete Reference','Herbert Schildt','Programming'],['Python Crash Course','Eric Matthes','Programming'],['Data Structures and Algorithms','Mark Allen Weiss','Computer Science'],['Design Patterns','Erich Gamma','Software Engineering'],['Digital Logic Design','Morris Mano','Electronics'],['Engineering Mathematics','G. S. Rao','Mathematics'],['Web Technologies','Uttam K. Roy','Information Technology'],['Cloud Computing','Rajkumar Buyya','Computer Science'],['Machine Learning','Tom Mitchell','Computer Science'],['Software Testing','Ron Patton','Software Engineering'],['Computer Architecture','Morris Mano','Computer Science'],['Operating Systems','William Stallings','Computer Science'],['Full Stack Development','Chris Minnick','Programming'],['Information Security','William Stallings','Cyber Security']];
for(let i=0;i<titles.length;i++){const [title,author,category]=titles[i];const b=await Book.create({title,author,isbn:`978000000${String(i+1).padStart(4,'0')}`,publisher:'Academy Press',edition:'1st',year:2024,category,department:'Engineering',description:`A carefully catalogued volume in the Enchanted Book Bank archive. Explore ${title} through a modern academic collection.`,shelf:`Building A → Floor ${1+(i%3)} → Section ${String.fromCharCode(65+i%5)} → Shelf ${10+i}`,totalCopies:3,availableCopies:3});for(let j=1;j<=3;j++)await BookCopy.create({book:b._id,accessionId:`ACC-${i+1}-${j}`,shelf:b.shelf})}
await Setting.create({maxActiveBooks:5,borrowDays:14,finePerDay:2,maxRenewals:1,institutionName:'The Enchanted Book Bank'});console.log('Seed complete');process.exit(0);
